#+STARTUP: showall
Updated: <2020-08-27>

* Enviroment
  - GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.17.3) of 2020-08-18
  - build branch: feature/native-comp commit 76faab2
  - system-configuration-options: ~--with-xwidgets --with-x-toolkit=gtk3 --with-nativecomp~
  - OS: Manjaro 20.0.3 Lysia
  - Shell: zsh 5.8
  - Kernel: 5.8.0-1-MANJARO
  - DE: Deepin
  - WM: KWin

* TODOs
  - [ ] fix emacs-ipython-notebook configurations

* Features
  - =org=
    - =org-mode=
      take note
    - =org-agenda=
      gtd
    - =org-babel=
      code blocks, also work well with jupyter
  - =latex=
    - =company-auctex=, =company-math=
      auto completion
    - =webkit-katex-render=
      real time latex preview at point
  - =client=
    - =restclient=
      client like postman
    - =websocket-client=
      client work with websocket protocol
  - =jupyter=
    - =emacs-jupyter=
      an interface to communicate with Jupyter kernels, provide jupyter-repl, org-jupyter integration
    - =emacs-ipython-notebook=
      Emacs IPython Notebook (EIN) lets you run Jupyter (formerly IPython) notebooks within Emacs
  - =editor enhancement=
    automatic parenthesis pairing, highlight ...
  - =package management=
    - =use-package=
      config packages
    - =quelpa-use-package=
      build and install package directly from source, such as github
  - =ui=
    - =all-the-icons=
      [[https://github.com/domtronn/all-the-icons.el#installing-fonts][Intalling Fonts]]
    - =doom-theme=
      fancy theme
    - =modeline=
      provide useful file information in the bottom
  - =emacs environment=
    - =exec-path-from-shell=
      copy system enviroment into emacs, such as PATH
  - =evil=
      emulates the main features of Vim
  - =leader key=
      press "SPC" in vim normal state just like spacemacs
  - =emacs enhancement=
    - =helpful=
      better *Help* buffer
    - =elisp-demos=
      display elisp examples in *Help* buffer
    - =ibuffer-vc=
      group buffers by project
    - =all-the-icons-dired=
      fantasy file manager
    - =eww=
      emacs web browser, not support js, but good for reading web doc
    - =fd-dired=
      Provide a dired-mode interface for [[https://github.com/sharkdp/fd][fd]]’s result. Same functionality as find-dired, using fd instead.
    - =tree-sitter=
      An incremental parsing library. It requires Emacs 25.1 or above, built with dynamic module support.
  - =neotree=
      A tree plugin like NerdTree for Vim
  - =shell and terminal=
    - =eshell=
      emacs shell
    - =emacs-libvterm=
      emacs libvterm intergration, great terminal in emacs, better than ansi-term
      [[https://github.com/akermu/emacs-libvterm][Installing Emacs-libvterm]]
  - =ivy=
      completion for emacs command
  - =programming=
    - =eglot/lsp-mode=
      language server support: code completion, reformat, find definitions, etc.
    - =dap-mode=
      debuger (require lsp-mode)
    - =projectile/project/find-file-in-project=
      project management and navigation \\
      find-file-in-project use [[https://github.com/sharkdp/fd][fd]] by default
    - =company-mode=
      code completion
    - =yasnippets=
      snippets
    - =magit=
      damn good git support
    - =paren, rainbow-mode=
      highlight parenthesis and color string
    - =zeal-at-point, helm-dash=
      offline documentation browser
      [[https://zealdocs.org/][Installing Zeal]]
    - =awesome-pair, lispy=
      structure edit
    - =symbol-overlay=
      highlight symbol, nice package for reading code
  - =docker=
    [[https://github.com/Silex/docker.el][docker]] for docker command, [[https://github.com/spotify/dockerfile-mode][dockerfile-mode]] for editing Dockerfile, [[https://github.com/meqif/docker-compose-mode][docker-compose-mode]] for editing docker-compose.yml
  - =others=
    - =eaf=
      emacs-application-framework for browsering web, previewing markdown, pdf ...
    - =elfeed=
      rss
    - =youdao-dictionary=
      translate english to chinese at point
    - =insert-translated-name=
      Insert translated string, type chinese insertd english for short
  - =portable dumper=

* Languages Support
** Features like auto complete, go to definitions, documentation on hover
  - [X] =C/C++= install [[https://github.com/MaskRay/emacs-ccls][emacs-ccls]]
  - [X] =Java= install [[https://github.com/emacs-lsp/lsp-java][lsp-java]]
  - [X] =Python= install [[https://github.com/emacs-lsp/lsp-pyright][lsp-pyright]] and `npm install -g pyright`
  - [X] =Rust= install [[https://rust-analyzer.github.io/manual.html#building-from-source][rust-analyzer]]
  - [X] =Go= install [[https://github.com/golang/tools/blob/master/gopls/doc/user.md#installation][gopls]]
  - [X] =Common-Lisp= install [[https://github.com/joaotavora/sly][sly]]
  - [X] =Julia= v1.5, using submodules/lsp-julia
  - [X] =Javascript/Typescript= npm i -g typescript typescript-language-server
  - [X] =Clojure/ClojureScript= [[https://github.com/snoe/clojure-lsp#installation][clojure-lsp]]
** Debugger
  - [X] =C/C++= install [[https://github.com/emacs-lsp/dap-mode#native-debug-gdblldb]['dap-gdb-lldb]]
  - [X] =Java= install [[https://github.com/emacs-lsp/dap-mode#java]['dap-java]]
  - [X] =Python= install [[https://github.com/emacs-lsp/dap-mode#python]['dap-python]]
  - [X] =Rust= install [[https://github.com/emacs-lsp/dap-mode#native-debug-gdblldb]['dap-gdb-lldb]]
  - [ ] =Go=
  - [ ] =Julia=
  - [ ] =Javascript/Typescript=

* Build Emacs

** Build Emacs 28
   #+begin_src shell
     git clone --depth 1 https://github.com/emacs-mirror/emacs.git
     cd emacs
     ./autogen.sh
     ./configure --with-xwidgets --with-x-toolkit=gtk3
     make -j8
     sudo make install
   #+end_src

** Or Install gccemacs, Bringing GNU Emacs to Native Code (Recommended)

   Install libgccjit first https://aur.archlinux.org/packages/libgccjit/

   #+begin_src shell
     git clone --depth 1 --branch feature/native-comp https://github.com/emacs-mirror/emacs.git emacs-native-comp
     cd emacs-native-comp
     ./autogen.sh
     ./configure --with-xwidgets --with-x-toolkit=gtk3 --with-nativecomp
     make -j8
     sudo make install
   #+end_src

* Installation
#+begin_src shell
  git clone --recursive https://github.com/zsxh/emacs.d.git ~/.emacs.d
#+end_src

* Updating
#+begin_src shell
  cd ~/.emacs.d/
  git pull
  git submodule update --init --recursive
#+end_src

* Display emacs build settings?
  =M-x describe-variable= =system-configuration-options=
